apiVersion: v1
kind: Service
metadata:
  labels:
    name: nginx
    purpose: srv demo
spec:
  type: NodePort
  selector:
    labels: nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 100    